name: ariat_app
description: "AIRAT-NA Tourist Navigation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  fluent_ui: ^4.13.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # State & DI
  provider: ^6.1.4

  # Networking
  http: ^1.4.0
  connectivity_plus: ^6.1.3

  # Local Storage & Cache
  shared_preferences: ^2.5.0
  sqflite: ^2.4.1
  path: ^1.9.0

  # Auth
  crypto: ^3.0.6

  # Location & Notifications
  geolocator: ^13.0.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
