name: ariat_na
description: "AIRAT-NA Tourist Navigation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.4.0
  shared_preferences: ^2.5.0
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
